/* eslint-env node */

module.exports = {
  components: {
    categories: [
      {
        name: 'General',
        include: [
          '../../components/accordion/src/template.tsx',
          '../../components/accordion/src/accordion-item/template.tsx',
          '../../components/alert/src/template.tsx',
          '../../components/breadcrumbs/src/template.tsx',
          '../../components/breadcrumbs/src/breadcrumbs-item/template.tsx',
          '../../components/button/src/template.tsx',
          '../../components/action-group/src/template.tsx',
          '../../components/card/src/template.tsx',
          '../../components/heading/src/template.tsx',
          '../../components/data-list/src/template.tsx',
          '../../components/data-list/src/data-list-item/template.tsx',
          '../../components/expandable-content/src/template.tsx',
          '../../components/header/src/template.tsx',
          '../../components/footer/src/template.tsx',
          '../../components/footer/src/footer-column/template.tsx',
          '../../components/footer/src/footer-item/template.tsx',
          '../../components/logo/src/template.tsx',
          '../../components/menubar/src/template.tsx',
          '../../components/menubar/src/menubar-item/template.tsx',
          '../../components/menubar-mobile/src/template.tsx',
          '../../components/icon/src/template.tsx',
          '../../components/status-icon/src/template.tsx',
          '../../components/status-indicator/src/template.tsx',
          '../../components/link/src/template.tsx',
          '../../components/tag/src/template.tsx',
          '../../components/table/src/template.tsx',
          '../../components/progress-tracker/src/template.tsx',
          '../../components/progress-tracker/src/progress-tracker-step/template.tsx',
          '../../components/hero/src/template.tsx',
          '../../components/horizontal-rule/src/template.tsx',
          '../../components/item-list/src/template.tsx',
          '../../components/ordered-unordered-list/src/template.tsx',
          '../../components/paragraph/src/template.tsx',
          '../../components/pagination/src/template.tsx',
          '../../components/tabs/src/template.tsx',
          '../../components/tabs/src/tab-item/template.tsx',
          '../../components/toggle/src/template.tsx',
        ],
      },
      {
        name: 'Forms',
        include: [
          '../../components/form-fieldset/src/template.tsx',
          '../../components/form-textinput/src/template.tsx',
          '../../components/form-field-textinput/src/template.tsx',
          '../../components/form-textarea/src/template.tsx',
          '../../components/form-field-textarea/src/template.tsx',
          '../../components/form-checkbox/src/template.tsx',
          '../../components/form-checkbox-group/src/template.tsx',
          '../../components/form-field-checkbox/src/template.tsx',
          '../../components/form-radio-button/src/template.tsx',
          '../../components/form-radio-button-group/src/template.tsx',
          '../../components/form-field-radio-button/src/template.tsx',
          '../../components/form-select/src/template.tsx',
          '../../components/form-field-select/src/template.tsx',
          '../../components/form-dateinput/src/template.tsx',
          '../../components/form-field-dateinput/src/template.tsx',
          '../../components/form-timeinput/src/template.tsx',
          '../../components/form-field-timeinput/src/template.tsx',
          '../../components/form-fileinput/src/template.tsx',
          '../../components/form-field-fileinput/src/template.tsx',
          '../../components/form-feedback/src/template.tsx',
          '../../components/form-field-label/src/template.tsx',
        ],
      },
      {
        name: 'Layout',
        include: [
          '../../components/max-width-layout/src/template.tsx',
          '../../components/form-layout/src/template.tsx',
          '../../components/scrollable-content/src/template.tsx',
          '../../components/sidebar-layout/src/template.tsx',
          '../../components/sidebar-layout/src/sidebar-layout-bar/template.tsx',
          '../../components/sidebar-layout/src/sidebar-layout-content/template.tsx',
          '../../components/layout-flow/src/template.tsx',
          '../../components/grid/src/template.tsx',
        ],
      },
    ],
    wrapper: './src/Wrapper/UXPinWrapper.tsx',
    webpackConfig: './webpack.config.js',
  },
  name: 'ROOS',
};
