export default {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order', 'stylelint-use-logical'],
  rules: {
    'alpha-value-notation': 'percentage',
    'at-rule-empty-line-before': null,
    'at-rule-no-unknown': null,
    'block-no-empty': true,
    'color-function-notation': 'modern',
    'color-no-invalid-hex': true,
    'comment-no-empty': true,
    'lightness-notation': null,
    'custom-property-pattern': '^_?(rvo|utrecht)-[a-z0-9-]+$',
    'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates-with-different-values'] }],
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-property-value-disallowed-list': {
      'text-align': ['left', 'right'],
    },
    'font-family-name-quotes': 'always-unless-keyword',
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'font-weight-notation': [
      'numeric',
      {
        ignore: ['relative'],
      },
    ],
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-url-no-scheme-relative': true,
    'function-url-quotes': 'always',
    'hue-degree-notation': 'number',
    'keyframe-declaration-no-important': true,
    'keyframes-name-pattern': '^(rvo|utrecht)-[a-z0-9-]+$',
    'length-zero-no-unit': [
      true,
      {
        ignore: ['custom-properties'],
      },
    ],
    'media-feature-name-no-unknown': true,
    'media-feature-range-notation': null,
    'no-descending-specificity': null,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': true,
    'no-invalid-double-slash-comments': true,
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-order': [
      {
        groupName: 'border',
        properties: [
          'border', // `border` before `border-*`
          'border-color', // `border-color` before `border-*-color`
          'border-radius', // `border-radius` before `border-*-radius`
          'border-style', // `border-style` before `border-*-style`
          'border-width', // `border-width` before `border-*-width`
          'border-bottom',
          'border-bottom-color',
          'border-bottom-left-radius',
          'border-bottom-right-radius',
          'border-bottom-style',
          'border-bottom-width',
          'border-left',
          'border-left-color',
          'border-left-style',
          'border-left-width',
          'border-right',
          'border-right-color',
          'border-right-style',
          'border-right-width',
          'border-top',
          'border-top-color',
          'border-top-left-radius',
          'border-top-right-radius',
          'border-top-style',
          'border-top-width',
          // CSS Logical properties after CSS Physical properties (typically used as fallback)
          'border-block', // `border-block` before `border-block-*`
          'border-block-color', // `border-block-color` before `border-block-*-color`
          'border-block-style', // `border-block-style` before `border-block-*-style`
          'border-block-width', // `border-block-width` before `border-block-*-width`
          'border-block-end',
          'border-block-end-color',
          'border-block-end-style',
          'border-block-end-width',
          'border-block-start',
          'border-block-start-color',
          'border-block-start-style',
          'border-block-start-width',
          'border-collapse',
          'border-image',
          'border-image-outset',
          'border-image-repeat',
          'border-image-slice',
          'border-image-source',
          'border-image-width',
          'border-end-end-radius',
          'border-end-start-radius',
          'border-inline',
          'border-inline-color', // `border-inline-color` before `border-inline-*-color`
          'border-inline-style', // `border-inline-style` before `border-inline-*-style`
          'border-inline-width', // `border-inline-width` before `border-inline-*-width`
          'border-inline-end',
          'border-inline-end-color',
          'border-inline-end-style',
          'border-inline-end-width',
          'border-inline-start',
          'border-inline-start-color',
          'border-inline-start-style',
          'border-inline-start-width',
          'border-spacing',
          'border-start-end-radius',
          'border-start-start-radius',
        ],
      },
    ],
    'order/properties-alphabetical-order': true,
    'property-no-unknown': true,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': null,
    'scss/at-extend-no-missing-placeholder': null,
    'scss/at-mixin-pattern': '^[a-z][a-z0-9-_]*$',
    'scss/at-rule-no-unknown': true,
    'scss/dollar-variable-default': null,
    'scss/dollar-variable-first-in-block': [true, { ignore: ['comments', 'imports'] }],
    'scss/dollar-variable-pattern': '^(rvo|utrecht)-[a-z0-9-]+$',
    'scss/operator-no-newline-after': null,
    'scss/percent-placeholder-pattern': '^(rvo|utrecht)-[a-z0-9-]+$',
    'selector-attribute-quotes': 'always',
    'selector-class-pattern': '^(rvo|utrecht)-[a-z0-9_-]+$',
    'selector-max-id': 0,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'string-no-newline': true,
    'unit-disallowed-list': ['s'],
    'unit-no-unknown': true,
    'value-keyword-case': ['lower', { camelCaseSvgKeywords: true }],
    'csstools/use-logical': 'always',
  },
};
