import React from 'react';
import MDXComponents from '@theme-original/MDXComponents';
import ComponentExample from '@site/src/components/ComponentExample';
import * as RVO from '@nl-rvo/component-library-react';

export default {
    ...MDXComponents,
    ComponentExample,
    Accordion: RVO.Accordion, 
    ActionGroup: RVO.ActionGroup,
    Alert: RVO.Alert,
    Breadcrumbs: RVO.Breadcrumbs,
    Button: RVO.Button,
    Card: RVO.Card,
    CardExperimental: RVO.CardExperimental,
    CheckBoxFilter: RVO.CheckBoxFilter,
    CounterBadge: RVO.CounterBadge,
    DataList: RVO.DataList,
    ExpandableContent: RVO.ExpandableContent,
    ExpandableTable: RVO.ExpandableTable,
    Favicon: RVO.Favicon,
    Footer: RVO.Footer,
    Autocomplete: RVO.Autocomplete,
    Checkbox: RVO.Checkbox,
    CheckboxGroup: RVO.CheckboxGroup,
    Dialog: RVO.Dialog,
    Feedback: RVO.Feedback,
    FormField: RVO.FormField,
    Fieldset: RVO.Fieldset,
    FileInput: RVO.FileInput,
    RadioButton: RVO.RadioButton,
    RadioButtonGroup: RVO.RadioButtonGroup,
    Select: RVO.Select,
    Textarea: RVO.Textarea,
    TextInput: RVO.TextInput,
    Grid: RVO.Grid,
    Header: RVO.Header,
    Heading: RVO.Heading,
    Hero: RVO.Hero,
    Hr: RVO.Hr,
    Icon: RVO.Icon,
    Image: RVO.Image,
    ItemList: RVO.ItemList,
    LayoutFlow: RVO.LayoutFlow,
    Link: RVO.Link,
    Loader: RVO.Loader,
    Logo: RVO.Logo,
    MaxWidthLayout: RVO.MaxWidthLayout,
    MenuBar: RVO.MenuBar,
    List: RVO.List,
    PageNumberNavigation: RVO.PageNumberNavigation,
    Paragraph: RVO.Paragraph,
    ProgressTracker: RVO.ProgressTracker,
    ProgressTrackerStep: RVO.ProgressTrackerStep,
    Quote: RVO.Quote,
    ScrollableContent: RVO.ScrollableContent,
    SidebarLayout: RVO.SidebarLayout,
    Skeleton: RVO.Skeleton,
    SkipLink: RVO.SkipLink,
    StatusIcon: RVO.StatusIcon,
    StatusIndicator: RVO.StatusIndicator, 
    Table: RVO.Table,
    Tabs: RVO.Tabs,
    Tag: RVO.Tag,
    Toggle: RVO.Toggle
};
