// @ts-check

// Parse all page categories as sidebar config
const path = require('path');
const { getDirectories } = require('./utils');

const sections = path.resolve(__dirname, '../../../documentation/pages');
const sidebarConfig = getDirectories(sections).reduce((sidebarConfig, section) => {
  sidebarConfig[section] = [{ type: 'autogenerated', dirName: section }];
  return sidebarConfig;
}, {});

module.exports = sidebarConfig;
