import path from 'path';
import { getDirectories } from './utils';

const sections = path.resolve(__dirname, '../../../documentation/pages');
const sidebarConfig = getDirectories(sections).reduce((sidebarConfig, section) => {
  sidebarConfig[section] = [{ type: 'autogenerated', dirName: section }];
  return sidebarConfig;
}, {});

export default sidebarConfig;
