import { IScrollableContentProps } from './';

export const defaultArgs: IScrollableContentProps = {
  content:
    'Deze scrollable content container heeft een hoogte van 300 pixels.<br/><br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sem ante, lacinia in pellentesque vel, bibendum id nisl. Quisque nisi felis, interdum in feugiat id, porta nec velit. Sed eu congue urna. Morbi sagittis massa vel nisl convallis ornare. Maecenas tempus eleifend metus quis commodo. Nullam tincidunt feugiat nunc, ut pretium purus mattis nec. Phasellus diam metus, hendrerit at posuere quis, rhoncus vitae magna. Donec hendrerit metus non accumsan fringilla. Quisque varius quis mauris ac congue. Phasellus non tellus quis velit fringilla consequat. Proin tempus erat velit, ac mollis dui molestie quis. In rutrum bibendum mi, ac eleifend nisl.<br/><br/>Vivamus maximus lobortis elit, commodo varius libero venenatis sed. Fusce rhoncus, mauris in imperdiet pulvinar, quam eros dignissim mi, vitae venenatis lorem justo quis ligula. Fusce ornare rhoncus elit, vel rhoncus mauris gravida at. Mauris non metus interdum, pharetra felis ac, pulvinar enim. Proin elementum vulputate arcu, at hendrerit metus aliquam ac. Quisque ullamcorper imperdiet nulla, vel faucibus urna congue nec. Vivamus vel enim aliquet, egestas erat id, scelerisque ex. Quisque leo diam, interdum id accumsan quis, fermentum eget ex. Quisque quis ipsum commodo lorem euismod pharetra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In non scelerisque est. Sed consequat ante vitae ornare accumsan. Mauris imperdiet, lorem at consequat pellentesque, ipsum felis pharetra ante, eu dictum mauris nisl sed lorem.<br/><br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus id mattis elit, cursus condimentum nisl. Vestibulum ultrices sem ligula, eget maximus orci lobortis vitae. Duis auctor tortor ac imperdiet dapibus. Quisque eu mi elit. In ornare quam arcu, eget laoreet magna iaculis vitae. Cras laoreet ligula sit amet faucibus tempus. Nulla odio augue, accumsan vitae libero tincidunt, consectetur elementum leo. Nullam venenatis elementum efficitur. Nunc nec ante nulla. Quisque turpis odio, consequat ut ultrices nec, elementum ultrices libero. Aliquam mollis rutrum efficitur.',
  height: 300,
  useAsMinimumHeight: false,
  disableScroll: false,
  useStyleAttribute: false,
};
